# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!


target 'MixfaderSample' do
	platform :ios, '8.0'
	pod 'MixfaderSDKCocoa'#, :path => '/Users/Jeanbaptistefabre/Work/MixfaderSDKCocoa'
end


